version: "3.8"

services:
  worker-app:
    container_name: worker-app
    build:
      context: .
      dockerfile: docker/golang/Dockerfile
    volumes:
      - .:/app2
    ports:
      - "8000:8000"
    networks:
      - worker-network


networks:
  worker-network:
    name: rabbitmq_network
    external: true
