version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.9.9-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    - RABBITMQ_DEFAULT_VHOST=/
    volumes:
    - ./docker/rabbitmq_data:/var/lib/rabbitmq
    networks:
    - stackBuilder-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - stackBuilder-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.8.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - stackBuilder-network

networks:
  stackBuilder-network:
    driver: bridge
    name: stackBuilder_network

volumes:
  elasticsearch-data-volume:
    driver: local
