version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.9.9-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    - RABBITMQ_DEFAULT_VHOST=/
    volumes:
    - ./docker/rabbitmq_data:/var/lib/rabbitmq
    networks:
    - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
    name: rabbitmq_network
