basePath: /api/v1
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  title: Swagger Documentation for Golang web API(Gin framework)
  version: "1.0"
paths: {}
swagger: "2.0"
