name: Haminjast-CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    working-directory: ./src/MainServices
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
      - name: verify dependencies
        run: go mod verify
        working-directory: ./src/MainService
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: mohammadali2001/haminjast
            tags: v1, latest
            registry: docker.io
            dockerfile: ./src/MainService/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
